
PORT_EXPLANATIONS = {
    20: "FTP data transfer traffic. FTP is outdated and insecure without encryption.",
    21: "FTP service. Can expose credentials if not secured.",
    22: "SSH service. Used for secure remote login.",
    23: "Telnet service. Not secure (no encryption).",
    25: "SMTP service. Used for sending emails.",
    53: "DNS service. Resolves domain names to IP addresses.",
    67: "DHCP server service.",
    68: "DHCP client service.",
    69: "TFTP service. Very basic and insecure.",
    80: "HTTP web server. Not encrypted.",
    110: "POP3 email retrieval.",
    123: "NTP time synchronization.",
    135: "RPC service (Windows).",
    137: "NetBIOS Name Service.",
    138: "NetBIOS Datagram Service.",
    139: "NetBIOS Session Service.",
    143: "IMAP email service.",
    161: "SNMP monitoring service.",
    389: "LDAP directory service.",
    443: "HTTPS secure web server.",
    445: "SMB file sharing (risky if public).",
    587: "SMTP submission service.",
    993: "Secure IMAP.",
    995: "Secure POP3.",
    1433: "Microsoft SQL Server.",
    1521: "Oracle Database.",
    3306: "MySQL database.",
    3389: "Remote Desktop (RDP).",
    5432: "PostgreSQL database.",
    5900: "VNC remote desktop.",
    6379: "Redis database.",
    8080: "Alternate HTTP service.",
    8443: "Alternate HTTPS service."
}